---
repo-name: peripherals-git
categories:
- Version Control
display-name: Git
manufacturer: 
product:
description: Git is a distributed version-control system for tracking changes in source code during software development.